name: build erlang

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
    paths:
      - dev/erlang/**

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  push:
    name: "erlang:${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 22
          - 23
          - 24
    
    steps:
      - uses: actions/checkout@v4
    
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: docker/build-push-action@v6
        with:
          context: ./dev/erlang
          file: ./dev/erlang/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/goover/erlang:${{ matrix.tag }}
